# Generated by Django 4.2.7 on 2025-11-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0004_bedhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedhold',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beds.bed'),
        ),
    ]
